public enum GameMode
{
	TeamDeathmatch = 0,
	Classic = 1,
	KnifeMode = 2,
	AWPMode = 3,
	GunGame = 4,
	DeathRun = 5,
	Hunter = 6,
	ZombieSurvival = 7,
	RandomMode = 8,
	Deathmatch = 9,
	BunnyHop = 10,
	HungerGames = 11,
	Only = 12,
	Juggernaut = 14,
	Surf = 15,
	Bomb = 16,
	BuildBattle = 17,
	MiniGames = 18,
	Bomb2 = 19,
	Meeting = 20,
	Murder = 21,
	Escort = 22
}
